### ISSUE TITLE
On/off attributes use floating point attruis

### ISSUE THREAD

**Issue by pdmeyer** [pdmeyer/seq#22]
Limitation of rnbo-generated externals is that you don't get the nice toggle attruis

**Comment by jinpavg** [comment]
I remember this one coming up in the binge... and it makes sense given the RNBO generation. I think there were a couple of spots in help files where it still might be helpful to have a [toggle] object patched to "someattribute $1" message box in order to demonstrate the on/off nature of the attribute, even if the attribute is in actuality a 0..1. range.

**Comment by pdmeyer** [comment]
It would be nice to add an attribute of `param` in rnbo that allows you to define the `attrui` `displaymode`. But you can't do that, so for now I'll just make sure that help patches, example patches, and snippets use a suitable one.
